name: timepulse
description: A simple and professional stopwatch app using Flutter.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
